TRACKED_CLASS: [giraffe, person]

RECORD: False

PID_GAINS: [-0.0016, 0.002]

# INIT_POS: [-0.5, 0.9, 0.1]  # pan (-1:1), tilt (-1:1), zoom (0:1); 
INIT_POS: [-110.0, 44.9, 4.0]  # pan (-180.0:180.0), tilt (-45.0:45.0), zoom (0.0:25.0)

ORIENTATION: up  # left up down right

IP: 192.168.1.64
PORT: 80

USER: admin        
PASS: NyalaChow22  

CONF_THRESHOLD: .5
NMS_THRESHOLD: .9
INPUT_WIDTH: 416
INPUT_HEIGHT: 416

MODEL_PATH: /home/ian/zooSpotter/models/
MODEL_CONFIG_FILE: yolov3-tiny.cfg
MODEL_WEIGHTS_FILE: yolov3-tiny.weights
CLASS_NAMES_FILE: coco.labels